-- Equipment catalog for autocomplete and data normalisation
CREATE TABLE IF NOT EXISTS equipment_catalog (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text NOT NULL,
  brand text NOT NULL,
  model text NOT NULL,
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(category, brand, model)
);

CREATE INDEX IF NOT EXISTS idx_equipment_catalog_cat ON equipment_catalog(category, brand);

ALTER TABLE equipment_catalog ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Equipment catalog is public" ON equipment_catalog FOR SELECT USING (true);
CREATE POLICY "Authenticated users can add equipment" ON equipment_catalog FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

-- Add new equipment fields to bow_setups
ALTER TABLE bow_setups ADD COLUMN IF NOT EXISTS arrow_rest jsonb;
ALTER TABLE bow_setups ADD COLUMN IF NOT EXISTS string jsonb;
ALTER TABLE bow_setups ADD COLUMN IF NOT EXISTS peep_sight jsonb;

-- Seed catalog
INSERT INTO equipment_catalog (category, brand, model, metadata) VALUES
-- Risers
('riser','Hoyt','Formula Xi','{"type":"recurve"}'),
('riser','Hoyt','Xceed','{"type":"recurve"}'),
('riser','Hoyt','Alero','{"type":"recurve"}'),
('riser','Win&Win','Meta DX','{"type":"recurve"}'),
('riser','Win&Win','ATF-X','{"type":"recurve"}'),
('riser','Win&Win','TFT-G','{"type":"recurve"}'),
('riser','MK Archery','MK Alpha','{"type":"recurve"}'),
('riser','MK Archery','MK Z','{"type":"recurve"}'),
('riser','MK Archery','MK Veracity','{"type":"recurve"}'),
('riser','Gillo','GQ','{"type":"recurve"}'),
('riser','Gillo','GT','{"type":"recurve"}'),
('riser','Gillo','G1','{"type":"recurve"}'),
('riser','Gillo','G2','{"type":"recurve"}'),
('riser','Fivics','Titan EX','{"type":"recurve"}'),
('riser','Fivics','Vellator V2','{"type":"recurve"}'),
('riser','Mybo','Elite','{"type":"recurve"}'),
('riser','Mybo','Origin','{"type":"recurve"}'),
('riser','Mybo','Wave','{"type":"recurve"}'),
('riser','Spigarelli','Explorer 2.0','{"type":"recurve"}'),
('riser','Spigarelli','Revolution','{"type":"recurve"}'),
('riser','WNS','Motive FX','{"type":"recurve"}'),
('riser','WNS','Delta FX','{"type":"recurve"}'),
('riser','WNS','Explore DX','{"type":"recurve"}'),
('riser','Kinetic','Stylized A1','{"type":"recurve"}'),
('riser','Kinetic','Vygo','{"type":"recurve"}'),
('riser','SF Archery','Forged+','{"type":"recurve"}'),
('riser','SF Archery','Optimo+','{"type":"recurve"}'),
('riser','Core','Jet Metal','{"type":"recurve"}'),
('riser','Core','Silhouette','{"type":"recurve"}'),
('riser','Galaxy','Crescent','{"type":"recurve"}'),
('riser','Galaxy','Ember','{"type":"recurve"}'),
('riser','Sebastien Flute','Zenith','{"type":"recurve"}'),
('riser','Uukha','Xpro3','{"type":"recurve"}'),
('riser','Hoyt','Invicta','{"type":"compound"}'),
('riser','Hoyt','Prevail','{"type":"compound"}'),
('riser','Hoyt','Pro Force FX','{"type":"compound"}'),
('riser','Mathews','TRX','{"type":"compound"}'),
('riser','PSE','Dominator Duo','{"type":"compound"}'),
('riser','PSE','Supra Focus','{"type":"compound"}'),
('riser','Bowtech','Reckoning','{"type":"compound"}'),
('riser','Elite','Echelon','{"type":"compound"}'),
('riser','Elite','Rezult','{"type":"compound"}'),
('riser','Prime','Nexus','{"type":"compound"}'),
('riser','Prime','CT9','{"type":"compound"}'),
-- Limbs
('limbs','Hoyt','Integra','{"material":"carbon/foam"}'),
('limbs','Hoyt','Velos','{"material":"carbon/foam"}'),
('limbs','Hoyt','Axia','{"material":"carbon/wood"}'),
('limbs','Win&Win','Wiawis NS-G','{"material":"carbon/foam"}'),
('limbs','Win&Win','Wiawis One','{"material":"carbon/foam"}'),
('limbs','Win&Win','Wiawis NS','{"material":"carbon/wood"}'),
('limbs','Win&Win','Wiawis RC One','{"material":"carbon"}'),
('limbs','MK Archery','MK Vera','{"material":"carbon/foam"}'),
('limbs','MK Archery','MK S75','{"material":"carbon/wood"}'),
('limbs','MK Archery','MK 1440','{"material":"carbon/foam"}'),
('limbs','Fivics','Titan EX','{"material":"carbon/foam"}'),
('limbs','WNS','Motive FX','{"material":"carbon/wood"}'),
('limbs','WNS','Delta FX','{"material":"carbon/wood"}'),
('limbs','WNS','Explore DX','{"material":"fibreglass"}'),
('limbs','Gillo','GS8','{"material":"carbon/wood"}'),
('limbs','Kinetic','Envy','{"material":"carbon/wood"}'),
('limbs','Kinetic','Novius II','{"material":"fibreglass"}'),
('limbs','SF Archery','Premium+','{"material":"carbon/wood"}'),
('limbs','SF Archery','Optimo+','{"material":"fibreglass"}'),
('limbs','Core','Jet Carbon','{"material":"carbon/wood"}'),
('limbs','Core','Silhouette','{"material":"fibreglass"}'),
('limbs','Galaxy','Silver Star','{"material":"fibreglass"}'),
('limbs','Galaxy','Bronze Star','{"material":"wood"}'),
('limbs','Mybo','Black Elk','{"material":"carbon/wood"}'),
('limbs','Spigarelli','Zen','{"material":"carbon/foam"}'),
('limbs','Uukha','VX+','{"material":"carbon"}'),
('limbs','Uukha','SX+','{"material":"carbon"}'),
('limbs','Uukha','EX1 Evo 2','{"material":"carbon"}'),
('limbs','Sebastien Flute','Premier','{"material":"carbon/wood"}'),
-- Sights
('sight','Shibuya','Dual Click',NULL),
('sight','Shibuya','Ultima RC II',NULL),
('sight','Shibuya','Ultima CPX',NULL),
('sight','Axcel','Achieve XP',NULL),
('sight','Axcel','Achieve CXL',NULL),
('sight','Axcel','AX2000',NULL),
('sight','Axcel','AccuTouch Carbon Pro',NULL),
('sight','Axcel','AX3000',NULL),
('sight','WNS','SPR-200',NULL),
('sight','Fivics','Titan',NULL),
('sight','Sure-Loc','Challenger',NULL),
('sight','Sure-Loc','Quest X',NULL),
('sight','Arc Systeme','SX200',NULL),
('sight','Cartel','Focus K',NULL),
('sight','CBE','Tek Target',NULL),
('sight','CBE','Vertex',NULL),
('sight','Spot Hogg','Fast Eddie',NULL),
('sight','Shrewd','Optum',NULL),
-- Arrows
('arrows','Easton','X10',NULL),
('arrows','Easton','X10 ProTour',NULL),
('arrows','Easton','ACE',NULL),
('arrows','Easton','Carbon One',NULL),
('arrows','Easton','Avance',NULL),
('arrows','Easton','Jazz',NULL),
('arrows','Easton','Neos',NULL),
('arrows','Easton','XX75 Platinum Plus',NULL),
('arrows','Easton','RX7',NULL),
('arrows','Easton','ProComp',NULL),
('arrows','Easton','FMJ',NULL),
('arrows','CarbonExpress','Nano Pro',NULL),
('arrows','CarbonExpress','Nano-XR',NULL),
('arrows','Victory','VAP TKO',NULL),
('arrows','Victory','VAP V1',NULL),
('arrows','Gold Tip','Pierce',NULL),
('arrows','Gold Tip','Pierce Platinum',NULL),
('arrows','Gold Tip','Airstrike',NULL),
('arrows','Black Eagle','PS23',NULL),
('arrows','Skylon','Radius',NULL),
('arrows','Skylon','Brixton',NULL),
('arrows','Skylon','Performa',NULL),
('arrows','Skylon','Edge',NULL),
('arrows','WNS','Archon',NULL),
('arrows','Avalon','Tec One',NULL),
-- Buttons
('button','Shibuya','DX Plunger',NULL),
('button','Shibuya','Ultima Plunger',NULL),
('button','Beiter','Beiter Plunger',NULL),
('button','AAE','Gold Micro',NULL),
('button','AAE','Champion II',NULL),
('button','Fivics','CEX-2000',NULL),
('button','WNS','SPR-200 Plunger',NULL),
('button','Cartel','Maxion',NULL),
('button','Spigarelli','Magnetic Plunger',NULL),
('button','Gillo','Magnetic Plunger',NULL),
-- Stabilisers
('stabiliser','Doinker','Platinum Hi-Mod',NULL),
('stabiliser','Doinker','Hero',NULL),
('stabiliser','Doinker','Estremo',NULL),
('stabiliser','Win&Win','Wiawis ACS-EL',NULL),
('stabiliser','Win&Win','Wiawis Nano Max',NULL),
('stabiliser','Fivics','CEX-2100',NULL),
('stabiliser','Bee Stinger','Premier Plus',NULL),
('stabiliser','Bee Stinger','MicroHex',NULL),
('stabiliser','Shrewd','S2 Series',NULL),
('stabiliser','Shrewd','Atlas',NULL),
('stabiliser','WNS','SFT-200',NULL),
('stabiliser','Mybo','Wave Carbon',NULL),
('stabiliser','CBE','Torx',NULL),
('stabiliser','Avalon','Tec X',NULL),
('stabiliser','Core','Air Stabiliser',NULL),
-- V-bars
('v_bar','Doinker','Platinum V-Bar',NULL),
('v_bar','Win&Win','Wiawis V-Bar',NULL),
('v_bar','Fivics','V-Bar',NULL),
('v_bar','Bee Stinger','V-Bar',NULL),
('v_bar','Shrewd','V-Bar',NULL),
('v_bar','WNS','SPR-200 V-Bar',NULL),
('v_bar','Mybo','V-Bar',NULL),
('v_bar','AAE','V-Bar',NULL),
('v_bar','Gillo','V-Bar',NULL),
('v_bar','CBE','Torx V-Bar',NULL),
-- Tabs
('tab','AAE','Elite Tab',NULL),
('tab','AAE','Cavalier Elite',NULL),
('tab','Fivics','Saker II',NULL),
('tab','Fivics','Saker IV',NULL),
('tab','Win&Win','Wiawis Finger Tab',NULL),
('tab','Beiter','Beiter Tab',NULL),
('tab','Soma','Acro Tab',NULL),
('tab','Soma','Ordo Tab',NULL),
('tab','WNS','Pro-Feel Tab',NULL),
('tab','Fairweather','Tab',NULL),
('tab','Bateman','Cordovan Tab',NULL),
('tab','Decut','NIKA Tab',NULL),
-- Release aids
('release_aid','TruBall','Fulkrum Flex',NULL),
('release_aid','TruBall','Boss X',NULL),
('release_aid','TruBall','HT Pro',NULL),
('release_aid','Carter','Wise Choice',NULL),
('release_aid','Carter','RX1',NULL),
('release_aid','Carter','Just Cuz',NULL),
('release_aid','Carter','Honey 2',NULL),
('release_aid','Stan','PerfeX',NULL),
('release_aid','Stan','SX4',NULL),
('release_aid','Stan','Jet',NULL),
('release_aid','Scott','Sigma',NULL),
('release_aid','Scott','Longhorn',NULL),
('release_aid','Spot Hogg','Wiseguy',NULL),
('release_aid','B3 Archery','Coop',NULL),
('release_aid','B3 Archery','Rival',NULL),
-- Clickers
('clicker','Shibuya','Ultima Clicker',NULL),
('clicker','Beiter','Clicker',NULL),
('clicker','AAE','Clicker',NULL),
('clicker','Win&Win','Clicker',NULL),
('clicker','WNS','Clicker',NULL),
('clicker','Hoyt','Clicker',NULL),
('clicker','Spigarelli','Magnetic Clicker',NULL),
-- Scopes
('scope','Axcel','AV Scope',NULL),
('scope','Axcel','CurlEye',NULL),
('scope','Specialty Archery','PXS Target Scope',NULL),
('scope','Specialty Archery','Super Ball',NULL),
('scope','CBE','Tek Hybrid Scope',NULL),
('scope','Shrewd','Optum Scope',NULL),
('scope','Ultraview','UV3',NULL),
('scope','Feather Vision','VerdePlus',NULL),
-- Arrow rests
('arrow_rest','Shibuya','Ultima Rest','{"type":"recurve"}'),
('arrow_rest','Hoyt','Super Rest','{"type":"recurve"}'),
('arrow_rest','AAE','Free Flyte','{"type":"recurve"}'),
('arrow_rest','Beiter','Rest','{"type":"recurve"}'),
('arrow_rest','Hamskea','Epsilon','{"type":"compound"}'),
('arrow_rest','Hamskea','Trinity Hunter','{"type":"compound"}'),
('arrow_rest','Hamskea','Hybrid Target Pro','{"type":"compound"}'),
('arrow_rest','QAD','UltraRest HDX','{"type":"compound"}'),
('arrow_rest','QAD','Integrate MX','{"type":"compound"}'),
('arrow_rest','AAE','Pro Blade','{"type":"compound"}'),
('arrow_rest','Spot Hogg','Edge','{"type":"compound"}'),
-- Slings
('sling','Beiter','Sling',NULL),
('sling','Win&Win','Wiawis Sling',NULL),
('sling','Fivics','Bow Sling',NULL),
('sling','Beiter','Finger Sling',NULL),
('sling','Socx','Finger Sling',NULL),
('sling','Easton','Finger Sling',NULL)
ON CONFLICT (category, brand, model) DO NOTHING;
